// ─── Life in the UK Master Summary — embedded content ───────────────────────
// Matches chapter numbering used in the 21-day tracker app

export const SUMMARY_CHAPTERS = [
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch1",
    title: "Ch.1 — Values & Principles",
    sections: [
      {
        heading: "The Four Fundamental British Values",
        type: "table",
        headers: ["Value", "What it means"],
        rows: [
          ["Democracy", "Citizens elect representatives; Parliament makes laws on their behalf"],
          ["Rule of Law", "Everyone — including the government — is subject to the law"],
          ["Individual Liberty", "Freedom to live your life within the law as you choose"],
          ["Mutual Tolerance", "Respect for those with different faiths, beliefs, and ways of life"],
        ],
      },
      {
        heading: "Rights guaranteed in the UK",
        type: "bullets",
        items: [
          "Freedom of speech and expression",
          "Freedom of religion (or no religion)",
          "Freedom of assembly and peaceful protest",
          "Equal treatment under the law",
          "Right to a fair trial",
          "Right not to be held without charge — Habeas Corpus Act 1679",
        ],
      },
      {
        heading: "Responsibilities of citizens",
        type: "bullets",
        items: [
          "Obey and respect the law",
          "Pay taxes honestly",
          "Vote in elections (encouraged, not legally required)",
          "Serve on a jury when summoned (compulsory)",
          "Treat others with fairness and respect",
        ],
      },
      {
        type: "tips",
        items: [
          "All four values appear on virtually every test — know them word-for-word",
          "Habeas Corpus (1679) = cannot be held without lawful charge — links to Rule of Law",
          "Jury service is compulsory when summoned. Voting is NOT legally compulsory.",
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch2",
    title: "Ch.2 — What is the UK?",
    sections: [
      {
        heading: "The Four Nations",
        type: "table",
        headers: ["Nation", "Capital", "Patron Saint / Date / Flower"],
        rows: [
          ["England", "London", "St George — 23 April — Rose"],
          ["Scotland", "Edinburgh", "St Andrew — 30 November — Thistle"],
          ["Wales", "Cardiff", "St David — 1 March — Daffodil"],
          ["Northern Ireland", "Belfast", "St Patrick — 17 March — Shamrock"],
        ],
      },
      {
        heading: "Key distinctions",
        type: "bullets",
        items: [
          "Great Britain = England + Scotland + Wales (does NOT include N. Ireland)",
          "United Kingdom = Great Britain + Northern Ireland",
          "Union Flag does NOT include Wales — Wales was already united with England when it was designed",
          "The Union Flag is also correctly called the Union Jack",
        ],
      },
      {
        heading: "Languages of the UK",
        type: "table",
        headers: ["Language", "Notes"],
        rows: [
          ["English", "Spoken across the whole UK"],
          ["Welsh (Cymraeg)", "~19% of people in Wales; compulsory in Welsh schools"],
          ["Scottish Gaelic", "Spoken by some communities in Scotland"],
          ["Irish (Gaeilge)", "Spoken by some communities in Northern Ireland"],
        ],
      },
      {
        heading: "Crown Dependencies & Overseas Territories",
        type: "table",
        headers: ["Category", "Details"],
        rows: [
          ["Crown Dependencies", "Isle of Man, Jersey, Guernsey — self-governing; NOT part of the UK"],
          ["British Overseas Territories", "14 territories including Gibraltar, Falkland Islands, Cayman Islands, Bermuda"],
        ],
      },
      {
        heading: "Key UK Facts",
        type: "bullets",
        items: [
          "Population: ~67 million",
          "Largest city: London (~9 million)",
          "Currency: Pound Sterling (£)",
          "Driving: left-hand side of the road",
          "Electricity: 240 volts; three-pin plugs",
          "Time zone: GMT (winter) / BST (summer)",
        ],
      },
      {
        type: "tips",
        items: [
          "Great Britain vs United Kingdom: one of the most common exam traps",
          "Union Flag does NOT represent Wales — Wales was already part of England when it was made",
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch3",
    title: "Ch.3 — History",
    sections: [
      {
        heading: "Prehistory & the Romans",
        type: "table",
        headers: ["Date", "Event"],
        rows: [
          ["~10,000 BC", "Ice Age ends; earliest settlers arrive in Britain"],
          ["~6,000 BC", "Britain separates from mainland Europe as sea levels rise"],
          ["~4,000 BC", "Neolithic farmers arrive; Stonehenge begun ~3,000 BC"],
          ["55 BC", "Julius Caesar visits Britain — raids but does NOT conquer"],
          ["43 AD", "Emperor Claudius — Roman conquest of Britain begins"],
          ["122 AD", "Hadrian's Wall built — to keep out the Picts (Scottish tribes)"],
          ["410 AD", "Romans leave Britain to defend Rome from Visigoths"],
        ],
      },
      {
        heading: "Anglo-Saxons, Vikings & Normans (410–1066)",
        type: "table",
        headers: ["Date", "Event"],
        rows: [
          ["5th–6th Century", "Anglo-Saxons (Angles, Saxons, Jutes) settle Britain"],
          ["Late 8th Century", "Viking raids begin; Danes settle parts of England (Danelaw)"],
          ["871–899", "Alfred the Great — King of Wessex; defeats Danes; promotes English culture"],
          ["1016–1035", "Canute (Cnut) — Danish king rules all of England"],
          ["1042", "Edward the Confessor — builds Westminster Abbey"],
          ["1066", "Harold II — last Anglo-Saxon king; killed at Battle of Hastings"],
          ["1066", "William the Conqueror wins Battle of Hastings — Norman Conquest"],
          ["1086", "Domesday Book — survey of all land ownership and taxes in England"],
        ],
      },
      {
        heading: "The Middle Ages (1066–1485)",
        type: "table",
        headers: ["Date", "Event"],
        rows: [
          ["1215", "Magna Carta — King John forced to sign; first document limiting royal power"],
          ["1265", "First Parliament — Simon de Montfort calls knights and townspeople"],
          ["1284", "Statute of Rhuddlan — Wales placed under English rule"],
          ["1314", "Battle of Bannockburn — Robert the Bruce defeats English; Scotland stays independent"],
          ["1348", "Black Death — kills approximately one third of the UK population"],
          ["1381", "Peasants' Revolt — led by Wat Tyler; protests against poll tax"],
          ["1415", "Battle of Agincourt — Henry V defeats the French"],
          ["1476", "William Caxton introduces printing press to England"],
          ["1455–1485", "Wars of the Roses — Lancaster (red rose) vs York (white rose)"],
          ["1485", "Battle of Bosworth Field — Henry VII defeats Richard III; Tudor dynasty begins"],
        ],
      },
      {
        heading: "The Tudors (1485–1603)",
        type: "table",
        headers: ["Monarch", "Key Facts"],
        rows: [
          ["Henry VII (1485–1509)", "First Tudor monarch; ends Wars of the Roses"],
          ["Henry VIII (1509–1547)", "Act of Supremacy 1534 — head of Church of England; 6 wives; dissolved monasteries"],
          ["Edward VI (1547–1553)", "Protestant son; Book of Common Prayer introduced"],
          ["Mary I (1553–1558)", "Catholic; burned ~300 Protestants — 'Bloody Mary'"],
          ["Elizabeth I (1558–1603)", "Protestant; never married ('Virgin Queen'); defeated Spanish Armada 1588"],
        ],
      },
      {
        heading: "Henry VIII's Six Wives — in order",
        type: "mnemonic",
        text: "Divorced / Beheaded / Died / Divorced / Beheaded / Survived",
        table: {
          headers: ["Wife", "Fate"],
          rows: [
            ["1. Catherine of Aragon", "Divorced — Henry wanted a son; Pope refused annulment"],
            ["2. Anne Boleyn", "Beheaded — accused of treason; mother of Elizabeth I"],
            ["3. Jane Seymour", "Died in childbirth — gave Henry his son (Edward VI)"],
            ["4. Anne of Cleves", "Divorced — Henry disliked her on sight"],
            ["5. Catherine Howard", "Beheaded — accused of adultery"],
            ["6. Catherine Parr", "Survived — outlived Henry"],
          ],
        },
      },
      {
        heading: "Stuarts, Civil War & Glorious Revolution (1603–1714)",
        type: "table",
        headers: ["Date", "Event"],
        rows: [
          ["1603", "James I — first Stuart; unites crowns of England and Scotland"],
          ["1605", "Gunpowder Plot — Guy Fawkes and Catholic conspirators fail to blow up Parliament"],
          ["1611", "King James Bible published"],
          ["1642–1651", "English Civil War — Royalists (Cavaliers) vs Parliament (Roundheads)"],
          ["1649", "Charles I EXECUTED — the only British monarch ever to be executed"],
          ["1649–1660", "Commonwealth — Oliver Cromwell rules as Lord Protector"],
          ["1660", "Restoration — Charles II returns; monarchy restored"],
          ["1666", "Great Fire of London — Wren rebuilds St Paul's Cathedral"],
          ["1679", "Habeas Corpus Act — forbids unlawful imprisonment"],
          ["1688", "Glorious Revolution — Parliament invites William of Orange to replace James II"],
          ["1689", "Bill of Rights — establishes Parliament's supremacy over the monarch"],
          ["1707", "Act of Union — England and Scotland united as Kingdom of Great Britain"],
        ],
      },
      {
        heading: "18th Century: Enlightenment, Empire & Industry",
        type: "table",
        headers: ["Date", "Event"],
        rows: [
          ["1721", "Robert Walpole — first Prime Minister"],
          ["1760s–1840s", "Industrial Revolution — Britain transforms from farming to factory economy"],
          ["1800", "Act of Union — Ireland joins; United Kingdom formed"],
          ["1805", "Battle of Trafalgar — Admiral Nelson defeats French/Spanish fleet; Nelson dies"],
          ["1807", "Slave Trade Act — slave trade abolished (William Wilberforce's campaign)"],
          ["1815", "Battle of Waterloo — Duke of Wellington defeats Napoleon"],
          ["1833", "Slavery Abolition Act — slavery abolished throughout British Empire"],
          ["1837–1901", "Queen Victoria — Empire at its peak; longest reign at the time"],
          ["1853", "Florence Nightingale transforms nursing in Crimean War"],
          ["1859", "Charles Darwin publishes 'On the Origin of Species'"],
        ],
      },
      {
        heading: "Key Industrial Figures",
        type: "table",
        headers: ["Person", "Contribution"],
        rows: [
          ["James Watt", "Improved the steam engine — core of the Industrial Revolution"],
          ["Richard Arkwright", "Developed the spinning frame; pioneer of the factory system"],
          ["George Stephenson", "Built first passenger steam railway (Stockton–Darlington, 1825)"],
          ["Robert Stephenson", "George's son; built the Rocket locomotive and major railway bridges"],
          ["Isambard Kingdom Brunel", "Great Western Railway, Clifton Suspension Bridge, SS Great Britain"],
          ["Adam Smith", "Scottish economist; 'The Wealth of Nations' 1776; father of modern economics"],
          ["William Wilberforce", "MP who campaigned to abolish the slave trade; succeeded 1807"],
          ["Florence Nightingale", "'Lady with the Lamp'; reformed nursing; Crimean War"],
        ],
      },
      {
        heading: "The 20th Century",
        type: "table",
        headers: ["Date", "Event"],
        rows: [
          ["1903", "Emmeline Pankhurst founds WSPU — suffragettes"],
          ["1913", "Emily Davison — suffragette killed at Epsom Derby"],
          ["1914–1918", "First World War — UK joins after Germany invades Belgium"],
          ["1918", "Women over 30 with property gain the right to vote"],
          ["1921", "Irish Free State created; Northern Ireland stays in the UK"],
          ["1928", "Equal Franchise Act — women vote on equal terms with men (age 21)"],
          ["1939–1945", "Second World War — UK joins after Germany invades Poland"],
          ["1940", "Winston Churchill becomes PM; Battle of Britain (RAF vs Luftwaffe)"],
          ["1944", "D-Day — Allied forces land in Normandy, France (6 June)"],
          ["1945", "VE Day (8 May); Clement Attlee wins election"],
          ["1948", "NHS created; Universal Declaration of Human Rights; Empire Windrush arrives"],
          ["1969", "Voting age lowered from 21 to 18"],
          ["1979–1990", "Margaret Thatcher — first female Prime Minister"],
          ["1989", "Tim Berners-Lee invents the World Wide Web"],
          ["1998", "Good Friday Agreement — peace deal for Northern Ireland"],
          ["1999", "Scottish Parliament and Welsh Assembly established (devolution)"],
        ],
      },
      {
        type: "tips",
        items: [
          "Caesar (55 BC) = visited only. Claudius (43 AD) = conquered. Big distinction.",
          "1649 = Charles I EXECUTED. The ONLY British monarch ever executed.",
          "1807 = slave TRADE abolished. 1833 = slavery itself abolished. Different years.",
          "1918 = women 30+ with property. 1928 = equal voting at 21. Two different years.",
          "Glorious Revolution (1688) = event. Bill of Rights (1689) = document.",
          "Battle of Trafalgar 1805: Nelson dies. Battle of Waterloo 1815: Wellington wins.",
          "NHS created 1948 by Clement Attlee's Labour government.",
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch4",
    title: "Ch.4 — Society, Culture & Sport",
    sections: [
      {
        heading: "Religion",
        type: "table",
        headers: ["Religion", "Notes"],
        rows: [
          ["Christianity", "Largest religion — Church of England (Anglican), Church of Scotland (Presbyterian), Roman Catholic, others"],
          ["Islam", "Second largest religion in the UK"],
          ["Hinduism", "Significant communities; large presence in Leicester and London"],
          ["Sikhism", "Large community especially in the Midlands"],
          ["Judaism", "Long-established community; around 250,000 people"],
          ["Buddhism", "Growing community across the UK"],
        ],
      },
      {
        heading: "Church of England vs Church of Scotland",
        type: "table",
        headers: ["", "Church of England", "Church of Scotland"],
        rows: [
          ["Head", "Monarch (Supreme Governor)", "No royal head — Monarch is an ordinary member"],
          ["Type", "Anglican", "Presbyterian"],
          ["Spiritual leader", "Archbishop of Canterbury", "Moderator of the General Assembly"],
          ["Lords Spiritual", "26 bishops sit in House of Lords", "No equivalent"],
        ],
      },
      {
        heading: "Customs & Traditions",
        type: "table",
        headers: ["Occasion", "Notes"],
        rows: [
          ["New Year's Day (1 Jan)", "Auld Lang Syne (Robert Burns). Hogmanay in Scotland on 31 Dec."],
          ["Valentine's Day (14 Feb)", "Cards and gifts to romantic partners"],
          ["Shrove Tuesday / Pancake Day", "Day before Lent — eating pancakes"],
          ["St David's Day (1 Mar)", "Wales — daffodils and leeks"],
          ["St Patrick's Day (17 Mar)", "N. Ireland / Irish community — parades, green"],
          ["Easter", "Christian festival — Jesus's resurrection. Hot cross buns, Easter eggs."],
          ["St George's Day (23 Apr)", "England — patron saint's day; often low-key"],
          ["May Day (1 May)", "Bank holiday; traditional maypole dancing"],
          ["Bonfire Night (5 Nov)", "Gunpowder Plot 1605 — fireworks, bonfires, Guy Fawkes effigies"],
          ["Remembrance Day (11 Nov)", "Two-minute silence at 11am; red poppies worn"],
          ["Christmas (25 Dec)", "Birth of Jesus; also widely celebrated secularly"],
          ["Boxing Day (26 Dec)", "Bank holiday; traditionally for giving to those less fortunate"],
        ],
      },
      {
        heading: "Sport",
        type: "table",
        headers: ["Sport", "Key Facts"],
        rows: [
          ["Cricket", "Originated in England; Lord's Cricket Ground (London) is the world's most famous ground"],
          ["Football", "Rules codified in England; Football Association (FA) founded 1863"],
          ["Rugby Union", "Six Nations annually; England won World Cup 2003"],
          ["Rugby League", "Separate code; strong in northern England; Super League"],
          ["Tennis", "Wimbledon — oldest Grand Slam; All England Club, London"],
          ["Golf", "Origins in Scotland; St Andrews = 'home of golf'"],
          ["Grand National", "Steeplechase horse race at Aintree, Liverpool"],
          ["Epsom Derby", "Flat race at Epsom, Surrey (where Emily Davison was killed, 1913)"],
          ["Olympics", "London hosted 1908, 1948, 2012 — UK won 65 medals in 2012"],
        ],
      },
      {
        heading: "Famous Britons — Arts & Literature",
        type: "table",
        headers: ["Person", "Contribution"],
        rows: [
          ["William Shakespeare", "Playwright/poet; born Stratford-upon-Avon 1564; Globe Theatre, London"],
          ["Geoffrey Chaucer", "Canterbury Tales — one of first major works in English"],
          ["Robert Burns", "Scotland's national poet; 'Auld Lang Syne'; Burns Night 25 January"],
          ["Jane Austen", "Pride and Prejudice, Sense and Sensibility"],
          ["Charles Dickens", "Oliver Twist, A Christmas Carol, Great Expectations"],
          ["Roald Dahl", "Charlie and the Chocolate Factory, Matilda; Welsh author"],
          ["Dylan Thomas", "'Do Not Go Gentle Into That Good Night'; Welsh poet"],
          ["JMW Turner", "Landscape painter; Turner Prize named after him"],
          ["John Constable", "'The Hay Wain'; English countryside landscapes"],
          ["Henry Moore", "Modernist sculptor; large abstract bronze figures"],
        ],
      },
      {
        heading: "Famous Britons — Science & Invention",
        type: "table",
        headers: ["Person", "Contribution"],
        rows: [
          ["Isaac Newton", "Laws of motion and gravity; Principia Mathematica 1687"],
          ["Charles Darwin", "'On the Origin of Species' 1859; theory of evolution"],
          ["Alexander Fleming", "Discovered penicillin 1928 — first antibiotic"],
          ["Alan Turing", "Father of computing; broke German Enigma code in WWII"],
          ["Tim Berners-Lee", "Invented the World Wide Web 1989"],
          ["Stephen Hawking", "'A Brief History of Time'; black holes; cosmology"],
          ["Francis Crick", "Co-discovered DNA double helix structure 1953"],
        ],
      },
      {
        heading: "Places of Interest",
        type: "table",
        headers: ["Place", "Notes"],
        rows: [
          ["Stonehenge", "Wiltshire; prehistoric monument; ~3,000 BC"],
          ["Tower of London", "Historic castle; holds the Crown Jewels"],
          ["Edinburgh Castle", "Overlooks Edinburgh; holds the Scottish Crown Jewels"],
          ["Snowdonia", "Mountain range and national park in Wales; highest peak in Wales"],
          ["Lake District", "National park in Cumbria; England's largest"],
          ["Giant's Causeway", "Coastal rock formation in N. Ireland; UNESCO World Heritage Site"],
          ["Loch Lomond", "Scotland's largest lake; in the Trossachs National Park"],
        ],
      },
      {
        type: "tips",
        items: [
          "FA founded 1863 — football rules codified in England",
          "Wimbledon = oldest Grand Slam tennis tournament; All England Club, London",
          "Church of England: Supreme Governor = Monarch. Church of Scotland: Monarch is NOT the head.",
          "Robert Burns: Auld Lang Syne, Burns Night (25 January)",
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch5",
    title: "Ch.5 — Government & the Law",
    sections: [
      {
        heading: "Parliament",
        type: "table",
        headers: ["Chamber", "Role"],
        rows: [
          ["House of Commons", "650 elected MPs; the most powerful chamber; forms the government"],
          ["House of Lords", "Unelected peers (life peers + some hereditary); revises and scrutinises legislation"],
          ["The Monarch", "Formally part of Parliament; grants Royal Assent to Bills to make them law"],
        ],
      },
      {
        heading: "Key Parliamentary Facts",
        type: "bullets",
        items: [
          "General elections: every 5 years under normal circumstances",
          "Voting system: First Past the Post (most votes in a constituency wins the seat)",
          "To vote: must be 18+, UK/Irish/qualifying Commonwealth citizen, and registered",
          "Prime Minister: leader of the party with majority of MPs in the Commons",
          "Cabinet: senior ministers; meets weekly; takes major policy decisions",
          "The Speaker: chairs Commons debates; must be strictly politically neutral",
          "Prime Minister lives at 10 Downing Street; Chancellor of the Exchequer at No. 11",
        ],
      },
      {
        heading: "Devolved Governments",
        type: "table",
        headers: ["Region", "Body", "Location", "Established"],
        rows: [
          ["Scotland", "Scottish Parliament", "Holyrood, Edinburgh", "1999"],
          ["Wales", "Senedd Cymru (Welsh Parliament)", "Cardiff Bay", "1999"],
          ["Northern Ireland", "Northern Ireland Assembly", "Stormont, Belfast", "1998"],
          ["London", "Greater London Assembly", "City Hall, London", "2000"],
        ],
      },
      {
        heading: "Courts — Criminal",
        type: "table",
        headers: ["Court level", "England, Wales & N. Ireland", "Scotland"],
        rows: [
          ["Minor offences", "Magistrates' Court (no jury)", "Sheriff Court / JP Court (no jury)"],
          ["Serious crimes", "Crown Court (jury trial)", "High Court of Justiciary (jury trial)"],
          ["Appeals", "Court of Appeal", "Court of Session (civil) / High Court of Justiciary (criminal)"],
          ["Final appeal", "UK Supreme Court", "UK Supreme Court (civil cases)"],
        ],
      },
      {
        heading: "Courts — Civil / Small Claims",
        type: "table",
        headers: ["Jurisdiction", "Small Claims Limit", "Court"],
        rows: [
          ["England & Wales", "Up to £10,000", "Small Claims Court"],
          ["Scotland", "Up to £5,000", "Sheriff Court"],
          ["Northern Ireland", "Up to £3,000", "Small Claims Court"],
        ],
      },
      {
        heading: "Juries — Critical Facts",
        type: "table",
        headers: ["Jurisdiction", "Jury Size", "Verdicts available"],
        rows: [
          ["England, Wales & N. Ireland", "12 jurors", "Guilty / Not guilty"],
          ["Scotland", "15 jurors", "Guilty / Not guilty / NOT PROVEN (unique to Scotland)"],
        ],
      },
      {
        heading: "Other Legal Facts",
        type: "bullets",
        items: [
          "Age of criminal responsibility: 10 in England, Wales and N. Ireland; 12 in Scotland",
          "Solicitor: gives legal advice; represents clients in lower courts",
          "Barrister: represents clients in higher courts; usually instructed by a solicitor",
          "Legal aid: government help for those who cannot afford legal fees",
          "Human Rights Act 1998 — incorporates European Convention on Human Rights into UK law",
          "Equality Act 2010 — protects against discrimination on 9 protected characteristics",
        ],
      },
      {
        heading: "The Police",
        type: "bullets",
        items: [
          "999 = emergency (police, fire, ambulance)",
          "101 = non-emergency police",
          "111 = NHS non-emergency medical advice",
          "England, Wales, N. Ireland: local police forces; each headed by a Chief Constable",
          "London: Metropolitan Police; headed by the Commissioner",
          "Scotland: Police Scotland — a single national force",
          "N. Ireland: Police Service of Northern Ireland (PSNI)",
        ],
      },
      {
        heading: "Practical UK Life",
        type: "table",
        headers: ["Topic", "Key Facts"],
        rows: [
          ["Council Tax", "Local tax based on property value band (A = lowest, H = highest)"],
          ["TV Licence", "Required for live TV and BBC iPlayer; criminal offence not to have one"],
          ["NHS prescriptions", "Free in Scotland, Wales and N. Ireland; charge applies in England"],
          ["Driving licence", "Must be 17 to learn to drive; 16 for mopeds"],
          ["MOT", "Annual roadworthiness test — required for vehicles over 3 years old"],
          ["National Lottery", "Must be 18+ to play (raised from 16 in 2021); established in 1994"],
          ["Income tax", "Collected by HMRC via PAYE (Pay As You Earn) for employees"],
          ["National Insurance", "Contributions fund NHS, state pension, and benefits"],
        ],
      },
      {
        type: "tips",
        items: [
          "CRITICAL: Jury size = 12 in England/Wales/NI; 15 in Scotland",
          "CRITICAL: Only Scotland has the 'not proven' verdict",
          "CRITICAL: Small claims = £10,000 (Eng/Wales), £5,000 (Scotland), £3,000 (NI)",
          "Age of criminal responsibility: 10 in Eng/Wales/NI; 12 in Scotland",
          "Scotland (1999) and Wales (1999) got devolution same year; N. Ireland was 1998",
          "NHS prescriptions are free in Scotland, Wales and N. Ireland — not England",
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch6",
    title: "Ch.6 — Key Dates Table",
    sections: [
      {
        heading: "Master timeline — cover the right column and test yourself",
        type: "table",
        headers: ["Date", "Event", "Key Detail"],
        rows: [
          ["55 BC", "Julius Caesar visits Britain", "Visits only — does NOT conquer"],
          ["43 AD", "Claudius — Roman conquest", "Emperor (not Caesar)"],
          ["122 AD", "Hadrian's Wall built", "To keep out the Picts"],
          ["410 AD", "Romans leave Britain", "To defend Rome"],
          ["871", "Alfred the Great", "King of Wessex; united England"],
          ["1066", "Battle of Hastings", "William I — Norman Conquest"],
          ["1086", "Domesday Book", "William I's land survey"],
          ["1215", "Magna Carta", "King John; limits royal power"],
          ["1265", "First Parliament", "Simon de Montfort"],
          ["1314", "Battle of Bannockburn", "Scotland stays independent"],
          ["1348", "Black Death", "~1/3 of UK population dies"],
          ["1476", "Printing press in England", "William Caxton"],
          ["1485", "Battle of Bosworth Field", "Henry VII; Tudor dynasty begins"],
          ["1534", "Act of Supremacy", "Henry VIII = head of Church of England"],
          ["1588", "Spanish Armada defeated", "Elizabeth I; Francis Drake"],
          ["1605", "Gunpowder Plot", "Guy Fawkes; failed Catholic plot"],
          ["1642", "English Civil War begins", "Royalists vs Parliament"],
          ["1649", "Charles I executed", "ONLY monarch ever executed"],
          ["1660", "Restoration", "Charles II; monarchy restored"],
          ["1666", "Great Fire of London", "Wren rebuilds St Paul's"],
          ["1679", "Habeas Corpus Act", "Cannot be held without charge"],
          ["1688", "Glorious Revolution", "William of Orange replaces James II"],
          ["1689", "Bill of Rights", "Parliament's power over monarch"],
          ["1707", "Act of Union", "England + Scotland = Great Britain"],
          ["1721", "First Prime Minister", "Robert Walpole"],
          ["1776", "'Wealth of Nations'", "Adam Smith; free-market economics"],
          ["1800", "Act of Union", "Ireland joins; UK formed"],
          ["1805", "Battle of Trafalgar", "Nelson defeats French; Nelson dies"],
          ["1807", "Slave trade abolished", "William Wilberforce"],
          ["1815", "Battle of Waterloo", "Wellington defeats Napoleon"],
          ["1833", "Slavery abolished", "Slavery ends across the Empire"],
          ["1837–1901", "Queen Victoria", "Empire at peak; longest reign at time"],
          ["1863", "FA founded", "Football rules codified in England"],
          ["1903", "WSPU founded", "Emmeline Pankhurst; suffragettes"],
          ["1913", "Emily Davison dies", "Epsom Derby; suffragette martyr"],
          ["1914–18", "First World War", "UK joins after Belgium invaded"],
          ["1918", "Women vote (30+)", "Property owners only"],
          ["1921", "Irish Free State", "N. Ireland stays in UK"],
          ["1928", "Women equal vote", "Age 21, same as men"],
          ["1928", "Penicillin discovered", "Alexander Fleming"],
          ["1939–45", "Second World War", "Churchill PM from May 1940"],
          ["1944", "D-Day", "Allied landings in Normandy; 6 June"],
          ["1945", "VE Day; Attlee PM", "8 May; NHS planned"],
          ["1948", "NHS created", "National Health Service; free care"],
          ["1948", "Empire Windrush", "Caribbean immigration to UK"],
          ["1969", "Voting age → 18", "Lowered from 21"],
          ["1979", "Thatcher becomes PM", "First female Prime Minister"],
          ["1989", "World Wide Web", "Tim Berners-Lee"],
          ["1998", "Good Friday Agreement", "Peace deal for N. Ireland"],
          ["1999", "Devolution", "Scottish Parliament; Welsh Assembly"],
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "ch7",
    title: "Ch.7 — High-Risk Checklist",
    sections: [
      {
        heading: "Use on Days 14, 16, 18 & 21 — tick when confident, circle when unsure",
        type: "checklist",
        groups: [
          {
            label: "British Values & Rights",
            items: [
              "Name all 4 British values: Democracy / Rule of Law / Individual Liberty / Mutual Tolerance",
              "Habeas Corpus Act = 1679 — forbids unlawful imprisonment",
              "Jury service = compulsory. Voting = NOT legally compulsory.",
              "Human Rights Act = 1998. Equality Act = 2010.",
            ],
          },
          {
            label: "The Four Nations",
            items: [
              "England: London, St George, 23 April, Rose",
              "Scotland: Edinburgh, St Andrew, 30 November, Thistle",
              "Wales: Cardiff, St David, 1 March, Daffodil",
              "N. Ireland: Belfast, St Patrick, 17 March, Shamrock",
              "Great Britain = England + Scotland + Wales (NOT N. Ireland)",
              "Union Flag does NOT include Wales",
            ],
          },
          {
            label: "History — Most Frequently Tested",
            items: [
              "1215 = Magna Carta (King John). Different from Bill of Rights (1689).",
              "1348 = Black Death — killed ~1/3 of UK population",
              "1485 = Battle of Bosworth Field — Henry VII; Tudor dynasty",
              "1534 = Act of Supremacy — Henry VIII head of Church of England",
              "1588 = Spanish Armada defeated — Elizabeth I",
              "1605 = Gunpowder Plot — Guy Fawkes",
              "1649 = Charles I executed — only monarch executed",
              "1666 = Great Fire of London — Wren rebuilds St Paul's",
              "1679 = Habeas Corpus Act",
              "1688 = Glorious Revolution (event). 1689 = Bill of Rights (document).",
              "1707 = Act of Union — England + Scotland = Great Britain",
              "1721 = Robert Walpole — first Prime Minister",
              "1805 = Trafalgar (Nelson dies). 1815 = Waterloo (Wellington wins).",
              "1807 = slave trade abolished. 1833 = slavery itself abolished.",
              "1903 = WSPU founded (Pankhurst). 1913 = Emily Davison dies at Epsom.",
              "1918 = women 30+ with property get the vote",
              "1928 = equal voting rights for women (age 21)",
              "1948 = NHS created (Attlee). Empire Windrush arrives.",
              "1989 = World Wide Web (Tim Berners-Lee)",
              "1998 = Good Friday Agreement. 1999 = Devolution (Scotland, Wales).",
            ],
          },
          {
            label: "Parliament & Government",
            items: [
              "House of Commons = 650 MPs; elected; most powerful",
              "House of Lords = unelected; revises laws",
              "PM at 10 Downing Street; Chancellor at No. 11",
              "General elections every 5 years; First Past the Post",
              "Scottish Parliament (1999). Welsh Senedd (1999). NI Assembly (1998).",
            ],
          },
          {
            label: "Courts & Juries — Most Commonly Confused",
            items: [
              "Jury size: England/Wales/NI = 12. Scotland = 15.",
              "Scotland ONLY has 'not proven' verdict (third option)",
              "Small claims: Eng & Wales = £10,000. Scotland = £5,000. NI = £3,000.",
              "Minor crimes: Magistrates' Court (Eng/Wales); Sheriff Court (Scotland)",
              "Serious crimes: Crown Court (Eng/Wales/NI); High Court of Justiciary (Scotland)",
              "Age of criminal responsibility: 10 in Eng/Wales/NI; 12 in Scotland",
            ],
          },
          {
            label: "Famous Britons",
            items: [
              "Robert Walpole = first PM (1721)",
              "William Wilberforce = slave trade abolition",
              "Florence Nightingale = nursing reform, Crimean War",
              "Emmeline Pankhurst = founded WSPU 1903",
              "Emily Davison = killed at 1913 Epsom Derby",
              "Alexander Fleming = penicillin, 1928",
              "Alan Turing = computing, codebreaking (Enigma)",
              "Tim Berners-Lee = World Wide Web, 1989",
              "Isambard Kingdom Brunel = Great Western Railway, Clifton Suspension Bridge",
              "Richard Arkwright = spinning frame; factory system",
              "James Watt = improved steam engine",
              "Adam Smith = 'Wealth of Nations' 1776; father of economics",
            ],
          },
          {
            label: "Henry VIII's Six Wives",
            items: [
              "Divorced / Beheaded / Died / Divorced / Beheaded / Survived",
              "Catherine of Aragon → Anne Boleyn → Jane Seymour → Anne of Cleves → Catherine Howard → Catherine Parr",
            ],
          },
          {
            label: "Sport, Culture & Practical",
            items: [
              "FA (Football Association) = founded 1863 in England",
              "Wimbledon = oldest Grand Slam tennis; All England Club, London",
              "London hosted the Olympics in 1908, 1948 and 2012",
              "Church of England: Supreme Governor = Monarch",
              "Church of Scotland: Monarch is NOT the head (key difference)",
              "NHS prescriptions: FREE in Scotland, Wales, NI. Charge in England.",
              "TV Licence: required for live TV and BBC iPlayer. Criminal offence.",
              "National Lottery: must be 18+ to play. Established 1994.",
            ],
          },
        ],
      },
    ],
  },
];
